package sistemacaja;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class frmAnular extends javax.swing.JDialog {

    conexion con = new conexion();
    String numeroRecibo =null;
    /**
     * Creates new form frmAnular
     */
    public frmAnular(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.lblMotivo.setVisible(false);
        this.txtMotivo.setVisible(false);
        this.btnAnular.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroRecibo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        btnAnular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNumSolicitud = new javax.swing.JLabel();
        lblNumDni = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemacaja/signo-admiracion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setText("ADVERTENCIA.  Los cambios efectuados en esta Ventana, no pueden deshacerse, debe tener cuidado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 499, 20));

        jLabel3.setText("de ANULAR un Recibo ya emitido.  Si esta seguro de efectuar estos cambios que no podran recuperarse.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 20));

        jLabel4.setText("Numero de Recibo a Anular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));
        getContentPane().add(txtNumeroRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 170, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMotivo.setText("Describa el motivo de la Anulación del Recibo.");
        jPanel1.add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        jScrollPane1.setViewportView(txtMotivo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 500, 180));

        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 130, 40));

        jLabel6.setText("Numero de Solicitud:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, -1));

        jLabel7.setText("Numero de DNI:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblNumSolicitud.setText("jLabel8");
        jPanel1.add(lblNumSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 140, -1));

        lblNumDni.setText("jLabel9");
        jPanel1.add(lblNumDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 550, 420));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 120, 30));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        numeroRecibo = this.txtNumeroRecibo.getText();
        try
        {
            con.conectar();
            ResultSet res = con.consulta("select numSol, numDNI from recibo where numRec = "+numeroRecibo+";");
            res.next();
            String solicitud = res.getString(1);
            String dni = res.getString(2);
                    
            this.lblNumSolicitud.setText(solicitud);
            this.lblNumDni.setText(dni);
            
        }catch(SQLException e)
        {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        int confirmacion1 = JOptionPane.showConfirmDialog(rootPane, "¿Los datos son los correctos?");
        if(confirmacion1 == 0)
        {
            this.lblMotivo.setVisible(true);
            this.txtMotivo.setVisible(true);
            this.btnAnular.setVisible(true);
            this.txtMotivo.requestFocus();
            
        }else
        {
            JOptionPane.showMessageDialog(rootPane, "Revise la informacion");
            this.lblMotivo.setVisible(false);
            this.txtMotivo.setVisible(false);
            this.btnAnular.setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        // TODO add your handling code here:
        
        int confirmacion2 = JOptionPane.showConfirmDialog(rootPane, "¿Realmente Desea Anular el Recibo "+this.txtNumeroRecibo.getText()+"?");
        numeroRecibo = this.txtNumeroRecibo.getText();
        String motivo = this.txtMotivo.getText();
        if(confirmacion2 == 0)
        {
            try
            {
                con.conectar();
                con.insertar("INSERT INTO anular (codAnu, fecha, asunto, codRub,  codRec,codPer) VALUES (null, now(), '"+motivo+"', 0, "+numeroRecibo+", 1101);");
                con.cierraConexion();
                JOptionPane.showMessageDialog(rootPane, "Recibo anulado con Exito");
                dispose();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAnular dialog = new frmAnular(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNumDni;
    private javax.swing.JLabel lblNumSolicitud;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNumeroRecibo;
    // End of variables declaration//GEN-END:variables
}
